### ISSUE TITLE
Implement the mailchimp worker

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-mailchimp-worker#1]

**Comment by j3k0** [comment]
Waiting for j3k0/ganomede-events#3

**Comment by elmigranto** [comment]
Reading through Mailchimp API docs. Looks like what we need is [adding members to lists](http://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/). Perhaps we can implement [batching changes](http://developer.mailchimp.com/documentation/mailchimp/reference/lists/#create-post_lists_list_id), but let's leave it for later.

> Newsletter registration status will be stored as a `usermeta` in the **internal** metadata `newsletters`, with value `"<NEWSLETTER_NAME>"` (retrieve from environment variables). The `newsletters` metadata is a comma separated list of newsletter names.

So `alice:newsletters` would be `ganomede,triominos` (or perhaps list IDs from mailchimp would be a better idea)?

Looks like we need more than just `username -> subscribed to lists`. For example, when we add an email, mailchimp returns "Subscriber ID" which will be required to change email address or delete subscription. Or are we okay with adding multiple addresses of the same user into list (even so, I think it's better to have this mapping on our side as opposed to, say, using `username` as subscriber's first name for the list).

How is this list stays up-to-date (because I assume one may unsubscribe via link in email itself), are we adding webhooks later?

<hr/>

For starters, we can do the following when receiving event:

 - receive event (new user | email change);
 - look into redis for existing subscription ID (because events can be received multiple times)
   - it exists — PATCH email address (only if there is a difference? can user change subscription email without us knowing, probably not, but not sure?);
   - no record — POST new member;
 - update redis accrodingly.

For that to work we'll have to store json in redis at `userId:newsletters:<mailchimp-list-id>` with something like:

``` js
{ "subscriptionId": "c5afaf2193dfcc269d5b",  // id of alice's mailchimp subscription
                                             // to that list
  "email": "alice@wonderland.com", // which email is currently we _think_ is in mailchimp
                                   // (can't be sure??)
  "subscribed": true  // whether or not we _think_ email is subscribed
                      // (can't be sure without syncing)
}
```

**Comment by j3k0** [comment]
A little thing first to be sure we're on the same page, this module don't store anything in redis (at least directly): it uses the ganomede-usermeta API.

The implementation can stay simple and doesn't have to consider edge cases:

 1. register the email to the list on `CREATED` events.
 1. keep the info that the user was registered.
 1. never re-register.

I'm thinking as well: no need to update when the email changed... We can keep that for later.

It's a good idea to keep the the mailchimp subscriber ID around, if we ever want to polish the implementation. So a internal usermeta `newsletters$<newsletter_name>` (1) with JSON as you described is a good idea, although I changed it to this:

```js
{
 "type": "mailchimp",
 "listId": "1232132132", // id the mailchimp list
 "subscriptionId": "c5afaf2193dfcc269d5b",  // id of alice's mailchimp subscription
                                             // to that list
}
```

Not storing `email` and `subscribed`, assuming is it possible to check the subscription information of a user using mailchimp's API. Can we?

Also, I'd rather not use mailchimp's list id as the primary key, for a reason: flexibility. Imagine the same newsletter is broadcast through different channel, we want our user to receive it through only one channel.

The `newsletters` usermeta will list all mailling lists the user once registered to.. the list might not be up-to-date (if user unsubscribe), but it's just here for indicative reasons.

(1) `$` is allowed where `:` isn't in usermeta keys).

**Comment by elmigranto** [comment]
I agree with everything.

 - So we don't care about aliases change, just new registrations?
 - About multiple backends (mailchimp, etc), we should be careful not to overwrite others, so we only act if `type === "mailchimp"`, otherwise, ignore event. (Not like we are going to need this in initial implementation since we ignore USER CHANGED, but note for the future.)

**Comment by j3k0** [comment]
addendum to the spec.

The `CREATE` event will change to look like this:

```js
{
    "channel": "users/v1",
    "from": "triominos", // XXX not the URL here, the app_name
    "type": "CREATE",
    "data": {
      "userId": "hrry23",
      "aliases": {
        "email": "hrry@email.com",
        "name": "hrry"
      },
      "metadata": { // XXX will also expose additional registration metadata
        "country": "UK",
        "yearofbirth": 1966,
        "newsletter": false
      }
    }
}
```

 * `from` has to be filled in mailchimp in some way
   * in a field type that can support multiple values
 * `country` and `yearofbirth` too
   * single value
 * don't register into mailchimp if `newsletter` is not `true`.

Apparently mailchimp dashboard allows to define custom data to attach to users, I hope the API as well.

**Comment by j3k0** [comment]
... or instead of extending the `CREATE` event, mailchimp module can load the data from ganomede-usermeta by itself.

But then it could be easy to fall into a race-condition trap (event emitted before additional usermeta are written)... The worker would have to wait until all 3 metadata are available before continuing... with some timeout..

What do you think? Extending the event seems easier.

**Comment by j3k0** [comment]
> just new registrations?

Yes. aliases change might be added later. Let's just make sure we'll have stored the required info to make it possible.

**Comment by elmigranto** [comment]
Who writes those metas and when? If `users` service, let's extend. If client app after registration (user registers first, than we ask him to fill out some stuff) , I don't see a difference on who waits for them, "users" or "worker".

I guess `users` already receives all that info inside reigstration request? And, if registration succeeds, writes those into metadata?

**Comment by elmigranto** [comment]
I see from https://github.com/j3k0/ganomede-users/issues/15 that users will also write metadata received as part of registration payload, so, yeah, extending event makes more sense.

**Comment by elmigranto** [comment]
I don't understand what you mean about `from` field. Event includes `users/v1` as `from`, I believe, do you mean we have to differentiate between "triominos" users and "other-app" users? What's in "from" then, `users/triominos`?

**Comment by elmigranto** [comment]
Oh, wait. `users/v1` is a channel, and `from` can be something else. It just so happens, they are currently the same. But again, we have same `users` for all apps… So… I'm confused :)

**Comment by j3k0** [comment]
> Users receives all that info inside registration request? And, if registration succeeds, writes those into metadata.

Yes. It's not in place, should come soon.

**Comment by j3k0** [comment]
There'll be multiple instances of `ganomede-users`: 1 per app.

`ganomede-directory` and `ganomede-events`: only 1 for all apps.

The `users/v1` channel will include all users-related events, for all app. To know which app wrote to this channel, read the `from` field. As far as the mailchimp worker is concern, it's just a raw string that can be anything.

Event-emitter side as well also, it's just defined by a env variable. We can set something like "triominos/prod/users" (or any other convention decided by system admin).

**Comment by elmigranto** [comment]
So you mean something like if `someEnvVar === from`, then subscribe to newsletter? And maybe if `someEnvVar is missing`, then subscribe to newsletter. (So we can have per-app and all-app newsletters, like triominos updates and for-everyone developer newsletter)

**Comment by j3k0** [comment]
`someEnvVar in [from, undefined]` then subscribe: I didn't mean that but could be nice and easy to add.

What newsletters administrator wants, is that `from` is stored as a user field in mailchimp (so he can filter to send a mail only to users that registered through "gameX")

**Comment by elmigranto** [comment]
> What newsletters administrator wants, is that `from` is stored as a user field in mailchimp

Here's what I found out and implementing, so we are on the same page for this regarding mailchimp API. There are 3 entities we use:

 - list — the list of subscribers
 - segment — subset of that list
 - merge_field — some info about subscriber that we can set

There are 2 kinds of merge fields — system-wide and list-wide. Looks like we can only add custom ones to latter. So to achieve our goal, we do something like:

 1. create a list;
 1. add a merge_field named `G_VIA` to the list (value would be event's `from`, meaning "this user subscribed to the list from app", but there is severt char limit);
 1. create segment of that list with something like "`G_VIA` starts with `triominos/`";
 1. use that list segment when creating campaign or sending letters.

It's important to do 1) and 2) before adding subscribers, because uknown merge fields are ignored. I'll add a warning to logs and save info to redis, but not much else is possible.

**Comment by elmigranto** [comment]
I assume we added metadata to the event for the same kind of thing, so we want to store it in mailchimp. I'll add merge fields those correspond to a bit later (haven't looked which ones yet).

**Comment by j3k0** [comment]
Just out of curiosity, is it possible to add `merge_fields` to mailchimp from the API?

Metadata will be `country` and `birth`. Those might be "first-class" fields in mailchimp?

**Comment by j3k0** [comment]
Quick concept-map to get the full picture:

![mailchimp-registration](https://cloud.githubusercontent.com/assets/191881/23993526/9141a7bc-0a49-11e7-96b9-94672fd27b04.png)

**Comment by elmigranto** [comment]
> Just out of curiosity, is it possible to add `merge_fields` to mailchimp from the API?

~I would think so.~ [Yep](http://developer.mailchimp.com/documentation/mailchimp/reference/lists/merge-fields/).

> Metadata will be `country` and `birth`. Those might be "first-class" fields in mailchimp?

Last/First name and email is all personal info in merge_tags there is by default. There are `language` ([ISO code](http://kb.mailchimp.com/lists/manage-contacts/view-and-edit-subscriber-languages#Language-codes), maybe we can pack country into these, but I'd rather have custome one) and `latitude` / `longitude` on subscriber; though, geocoordinates are not very helpful for "email all users from France":

<img width="680" alt="screenshot 2017-03-16 19 50 22" src="https://cloud.githubusercontent.com/assets/886388/24002158/d4f96ee4-0a81-11e7-9b38-91572041a64c.png">

Overall, merge fields are like substitute values for email templates, so we'll probably have to create custom ones for segmenting based on personal info.

[Full list of merge fields](http://kb.mailchimp.com/merge-tags/all-the-merge-tags-cheat-sheet)
[Props for subscriber]( http://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/#create-post_lists_list_id_members)

**Comment by elmigranto** [comment]
Oh, wait, lat/long are actually what we need! Do we have coordinates (we might just translate country to capital lat/long)?
<img width="889" alt="screenshot 2017-03-16 19 57 48" src="https://cloud.githubusercontent.com/assets/886388/24002564/e5d53558-0a82-11e7-827a-bfa0fa7b893a.png">

**Comment by j3k0** [comment]
We don't have coordinates, but might very well find a way to them.

Mailchimp worker can check presence of "longitude" and "latitude" metadata, if not found, check "country" and put user at the capital city. `country` will be the country code.

I dig this out: http://techslides.com/demos/country-capitals.json

Has what we need.

**Comment by elmigranto** [comment]
We might also just have own field like `G_COUNTRY`. I'm guessing we're adding `G_YOB` for year of birth?

Other than that, tying everything together, will finish tomorrow. If you have a moment, please look through [config in README](https://github.com/j3k0/ganomede-mailchimp-worker/blob/develop/README.md#configuration), especially mailchimp/events part, and see if anything looks wierd to you.

**Comment by elmigranto** [comment]
Alright, things can be tested! It's in orphan branch `develop` and there is https://github.com/j3k0/ganomede-events/pull/22 to merge before, though. For now we have this (3-rd row):

<img width="1160" alt="screenshot 2017-03-20 15 52 51" src="https://cloud.githubusercontent.com/assets/886388/24096889/4ad35d2c-0d85-11e7-9e58-3895bd33f270.png">

Further work:

  - [x] bind everything to run from `index.js`. For now you have to `node src/worker.js`;
  - [x] derive and fill in coordinates (in order: explicitly in event's `metadata`; derived from `country`) — I'll need of country codes we use to match to that JSON you linked;
  - [ ] test and/or create merge fields so user doesn't have to do it manually;
  - [x] more printing of different operational stuff (for now it's only errors and warnings) and maybe add some stats (like 100 of latest subscriptions with timestamps).

**Comment by elmigranto** [comment]
Going to do first one ASAP (and maybe last one if that's not too much).

**Comment by j3k0** [comment]
> derive and fill in coordinates (in order: explicitly in event's metadata; derived from country) — I'll need of country codes we use to match to that JSON you linked;

`country` metadata already contains the country code.

> test and/or create merge fields so user doesn't have to do it manually;

if easy it's a good idea too, prevents human mistakes.

> stats

See ganomede-users's `statsd-wrapper.coffee`, usage:

```js
stats = require('./statsd-wrapper').createClient();
stats.increment('mailchimp.registrations.success');
stats.increment('mailchimp.registrations.failure');
```

It's short, conversion to ES6 should be quick. With that in place, we can setup statsd monitors on `failure / success rate` and `success / hour rate` to be sure worker is up, running and happy.

**Comment by elmigranto** [comment]
> country metadata already contains the country code.

Yeah, but JSON with capitals is country name.

**Comment by elmigranto** [comment]
What is country code format / standard?

**Comment by j3k0** [comment]
JSON seems to have it all (see `"CountryCode"`):

<img width="443" alt="screen shot 2017-03-20 at 22 12 41" src="https://cloud.githubusercontent.com/assets/191881/24119586/72041c30-0dba-11e7-9720-fd583e3f336f.png">

Format ISO something 2 letters codes.

**Comment by elmigranto** [comment]
Idk, we have `UK`, JSON wants `GB`:

``` json
{
  "CountryName": "United Kingdom",
  "CapitalName": "London",
  "CapitalLatitude": "51.5",
  "CapitalLongitude": "-0.083333",
  "CountryCode": "GB",
  "ContinentName": "Europe"
}
```

**Comment by elmigranto** [comment]
[This](https://en.wikipedia.org/wiki/ISO_3166-1) says `GB` is correct one, so I guess `UK` was a mistake in example?

**Comment by elmigranto** [comment]
I'm wondering about Statsd prefix, what I did:

``` js
statsd = new Client({prefix: process.env.STATSD_PREFIX});
statsd.increment('success');
// my understanding that prefix will include `mailchimp.registrations.` part
// (with a dot at the end? :)
```

**Comment by elmigranto** [comment]
Okay we can merge and see it in action, will add merge fields creation a bit later.

**Comment by j3k0** [comment]
Indeed, `UK` was a mistake.

Yes, statsd prefix should include a '.' at the end.
