### ISSUE TITLE
Small question

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-mailchimp-worker#4]
Any reason why this is commented out? https://github.com/j3k0/ganomede-mailchimp-worker/blob/develop/src/serve.js#L45

(I just don't want to uncomment if there's one)

**Comment by elmigranto** [comment]
Yes. We don't fork in this one. If we fork worker, it'll process everything twice, and I don't thing there's much point to to fork ping/about.

I was going to change all those unhandled exception things to simply restart server within a process, but later, and I don't thing those two are gonna throw anything.

**Comment by elmigranto** [comment]
Let's just run HTTP server in forked process.
