### ISSUE TITLE
Crash when STATSD is not defined

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-mailchimp-worker#5]
README claims that it can be optional, but it seems like it isn't... or I missed something.

```
src/worker.js:30
    this.statsd.increment('events');
                ^
TypeError: this.statsd.increment is not a function
```

**Comment by j3k0** [comment]
Here it is
https://github.com/j3k0/ganomede-mailchimp-worker/blob/develop/src/worker.js#L8

I fixed and will commit/push once everything work.

Those kind of issues have been happening a lot recently (that's why I'm adding full stack automated test).

Easier that automated full stack tests, you can also setup some manual full stacks testbeds: start the servers, `curl` some test requests, check that nobody crashed.

**Comment by elmigranto** [comment]
Was this an issue or something else?
<img width="352" alt="screenshot 2017-03-24 01 42 57" src="https://cloud.githubusercontent.com/assets/886388/24269486/472d7a58-1033-11e7-940a-4cbfd84cbc66.png">

**Comment by j3k0** [comment]
This was the main issue (probably the only issue, I don't remember if there was something else).
