### ISSUE TITLE
Worker crashes when event isn't complete

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-mailchimp-worker#8]
Older clients won't fill-in the metadata, the worker shouldn't crash.

More generally, incorrect payloads shouldn't crash the worker, it should just ignore the incoming event with a warning.

```
/home/app/code/src/objects.js:72                                                                                                  [92/454]
      G_COUNTRY: subscriptionRequest.metadata.country,
                                             ^

TypeError: Cannot read property 'country' of undefined
    at new MailchimpPayload (/home/app/code/src/objects.js:72:46)
    at MailchimpClient.subscribe (/home/app/code/src/apis/MailchimpClient.js:19:21)
    at steps (/home/app/code/src/SubscribesUsers.js:64:39)
    at /home/app/code/src/SubscribesUsers.js:26:13
    at nextTask (/home/app/code/node_modules/async/dist/async.js:5070:14)
    at /home/app/code/node_modules/async/dist/async.js:5064:13
    at apply (/home/app/code/node_modules/async/dist/async.js:21:25)
    at /home/app/code/node_modules/async/dist/async.js:56:12
    at /home/app/code/node_modules/async/dist/async.js:843:16
    at steps (/home/app/code/src/SubscribesUsers.js:62:9)
```

**Comment by j3k0** [comment]
Side issue with this worker crash, yet quite major:

 1. the worker fails to process the event and crash
 2. the event stays in queue 
 3. a new worker is spawned when irresponsiveness is detected
 4. newly spawn worker will crash on the same event, loop to step 3 forever

**Comment by elmigranto** [comment]
About forever loop. Not much we can do in this module itself, so:

 - don't crash;
 - log and ignore failing events (that's the plan!).

**Comment by elmigranto** [comment]
I mean we can do some kind of queue with retries and 2 processes (1st: receive, put in queue; 2nd: try N times, give up), but that's too much, I think.

**Comment by j3k0** [comment]
Yes, no need for complex solutions. Missing a few people in mailchimp is ok.
